name: pytest_and_coverage

on: [push]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd server
          poetry export -f requirements.txt --output requirements.txt
          pip install -r requirements.txt
      - name: pytest
        run: |
          coverage run -m pytest
      - name: Coverage report
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
